<?php
/**
 * Copyright © Open Techiz. All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 */

/** @var \Magentiz\GdprExtend\Block\Cookie $block */

/** @var \Mageplaza\GdprPro\Helper\Data $gdprHelper */
$gdprHelper = $this->helper(\Mageplaza\GdprPro\Helper\Data::class);

/** @var \Magento\Cookie\Helper\Cookie $cookieHelper */
$cookieHelper = $this->helper(\Magento\Cookie\Helper\Cookie::class);

if ($gdprHelper->isEnableCookieRestrictrion()): ?>
    <div class="message global gdpr-notice-cookies <?= /** @noEscape */ $gdprHelper->getHtmlClass() ?>" id="gdpr-notice-cookie-block"
         style="display: none">
        <div class="content">
            <?= /** @noEscape */ $gdprHelper->getCookieMessage() ?>
            <div class="actions">
                <?php if ($block->isEnableCookiePreferences()) : ?>
                <button id="gdpr-btn-cookie-config" class="action allow primary btn-cookie-config">
                    <span><?= /** @noEscape */ __('Configure') ?></span>
                </button>
                <?php endif; ?>
                <button id="gdpr-btn-cookie-allow" class="action allow primary">
                    <span><?= /** @noEscape */ $gdprHelper->getCookieButtonText() ?></span>
                </button>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#gdpr-notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#gdpr-btn-cookie-allow",
                    "cookieName": "<?= /** @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /** @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /** @noEscape */ $cookieHelper->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= /** @noEscape */ $block->getUrl('cookie/index/noCookies') ?>"
                }
            },
            "*": {
                "Magentiz_GdprExtend/js/cookie/preferences": {
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieLifetime": <?= /** @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>
                }
            }
        }
    </script>
    <?php if ($gdprHelper->isBlockAccess()): ?>
        <script type="text/javascript">
            window.gdprCookie = {
                url: "<?= /** @noEscape */ $gdprHelper->getCookiePolicyUrl() ?>",
                name: "<?= /** @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>"
            };
        </script>
    <?php endif; ?>
    <?php if ($customCss = $gdprHelper->getCustomCss()): ?>
        <style type="text/css">
            <?= /** @noEscape */ $customCss ?>
        </style>
    <?php endif; ?>
<?php endif; ?>


